[build]
  command = "npm run build"
  publish = "build/client"

# Redirect from /client/index.html to root
[[redirects]]
  from = "/client/*"
  to = "/:splat"
  status = 301
  force = true

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18" 